export const words = [
  { description: "apple" },
  { description: "banana" },
  { description: "cherry" },
  { description: "date" },
  { description: "elderberry" },
  { description: "fig" },
  { description: "grape" },
  { description: "honeydew" },
  { description: "kiwi" },
  { description: "lemon" },
  { description: "mango" },
  { description: "nectarine" },
  { description: "orange" },
  { description: "pear" },
  { description: "quince" },
  { description: "raspberry" },
  { description: "strawberry" },
  { description: "tangerine" },
  { description: "watermelon" },
];
